/**
 * CHAINTRACE // Seed Data: Verified VASP Intelligence & Segregated Demo Intelligence
 */

import {
  VaspEntity,
  WalletClusterEntity,
  VaspAddressEntity,
} from './types';

export const SEED_VASPS: VaspEntity[] = [
  {
    id: 'vasp-in-01',
    name: 'CoinDCX (Neblio Technologies)',
    legalName: 'Neblio Technologies Private Limited',
    country: 'India',
    jurisdiction: 'Bangalore / Mumbai (PMLA Compliant)',
    registrationStatus: 'REGISTERED',
    regulatoryIdentifier: 'FIU-IND-VDA-2023-0008',
    website: 'https://coindcx.com',
    status: 'ACTIVE',
    riskLevel: 'LOW',
    source: 'FIU-IND Public VDA Reporting Entity Registry',
    sourceType: 'verified_public_source',
    createdAt: '2023-08-01T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vasp-in-02',
    name: 'WazirX (Zanmai Labs)',
    legalName: 'Zanmai Labs Private Limited',
    country: 'India',
    jurisdiction: 'Mumbai (PMLA Compliant)',
    registrationStatus: 'REGISTERED',
    regulatoryIdentifier: 'FIU-IND-VDA-2023-0012',
    website: 'https://wazirx.com',
    status: 'ACTIVE',
    riskLevel: 'LOW',
    source: 'FIU-IND Public VDA Reporting Entity Registry',
    sourceType: 'verified_public_source',
    createdAt: '2023-08-01T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vasp-in-03',
    name: 'CoinSwitch Kuber (Bitcipher Labs)',
    legalName: 'Bitcipher Labs LLP',
    country: 'India',
    jurisdiction: 'Bangalore (PMLA Compliant)',
    registrationStatus: 'REGISTERED',
    regulatoryIdentifier: 'FIU-IND-VDA-2023-0004',
    website: 'https://coinswitch.co',
    status: 'ACTIVE',
    riskLevel: 'LOW',
    source: 'FIU-IND Public VDA Reporting Entity Registry',
    sourceType: 'verified_public_source',
    createdAt: '2023-08-01T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vasp-in-04',
    name: 'ZebPay (Awlencan Innovations)',
    legalName: 'Awlencan Innovations India Limited',
    country: 'India',
    jurisdiction: 'Ahmedabad (PMLA Compliant)',
    registrationStatus: 'REGISTERED',
    regulatoryIdentifier: 'FIU-IND-VDA-2023-0001',
    website: 'https://zebpay.com',
    status: 'ACTIVE',
    riskLevel: 'LOW',
    source: 'FIU-IND Public VDA Reporting Entity Registry',
    sourceType: 'verified_public_source',
    createdAt: '2023-08-01T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vasp-global-01',
    name: 'Binance Global Enclave',
    legalName: 'Binance Holdings Limited',
    country: 'Offshore (Cayman Islands)',
    jurisdiction: 'Decentralized / Offshore',
    registrationStatus: 'NOTICE_SERVED',
    regulatoryIdentifier: 'FIU-IND-SHOW-CAUSE-2023/88',
    website: 'https://binance.com',
    status: 'UNDER_INVESTIGATION',
    riskLevel: 'HIGH',
    source: 'Ministry of Finance / FIU-IND Section 69A IT Act Show Cause Order',
    sourceType: 'verified_public_source',
    createdAt: '2023-12-28T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vasp-global-02',
    name: 'HTX (Formerly Huobi)',
    legalName: 'HTX Global Limited (Seychelles)',
    country: 'Seychelles / Hong Kong',
    jurisdiction: 'Offshore Unregistered',
    registrationStatus: 'NON_COMPLIANT',
    regulatoryIdentifier: 'PENDING_STATUTORY_AUDIT',
    website: 'https://htx.com',
    status: 'SUSPENDED',
    riskLevel: 'CRITICAL',
    source: 'FIU-IND Non-Compliant Offshore VASP Directive',
    sourceType: 'verified_public_source',
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'vasp-global-03',
    name: 'Bybit Fintech Limited',
    legalName: 'Bybit Fintech BVI',
    country: 'Dubai (UAE) / BVI',
    jurisdiction: 'VARA / Offshore BVI',
    registrationStatus: 'NOTICE_SERVED',
    regulatoryIdentifier: 'FIU-NOTICE-VDA-2024-0019',
    website: 'https://bybit.com',
    status: 'UNDER_INVESTIGATION',
    riskLevel: 'HIGH',
    source: 'Statutory Notice FIU-NOTICE-VDA-2024-0019',
    sourceType: 'verified_public_source',
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
];

export const SEED_CLUSTERS: WalletClusterEntity[] = [
  {
    id: 'cluster-coindcx-poly-01',
    vaspId: 'vasp-in-01',
    name: 'CoinDCX Regulated Custody Cluster #POL-04',
    chain: 'polygon',
    confidence: 0.98,
    source: 'Investigator Subpoena Verification SEC-91',
    sourceType: 'investigator_verified',
    verificationStatus: 'verified',
    createdAt: '2025-06-10T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'cluster-wazirx-eth-01',
    vaspId: 'vasp-in-02',
    name: 'WazirX Omnibus Custody Cluster #ETH-02',
    chain: 'ethereum',
    confidence: 0.95,
    source: 'On-chain proof of reserves & statutory disclosure',
    sourceType: 'verified_public_source',
    verificationStatus: 'verified',
    createdAt: '2025-05-14T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'cluster-htx-tron-01',
    vaspId: 'vasp-global-02',
    name: 'HTX Offshore Hot Custody Deposit Pool',
    chain: 'tron',
    confidence: 0.92,
    source: 'Public sweep pattern analysis & exchange attestation',
    sourceType: 'verified_public_source',
    verificationStatus: 'verified',
    createdAt: '2025-08-20T00:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
];

export const SEED_ADDRESSES: VaspAddressEntity[] = [
  // 1. CoinDCX Polygon Custody Address (Verified)
  {
    id: 'addr-coindcx-01',
    vaspId: 'vasp-in-01',
    clusterId: 'cluster-coindcx-poly-01',
    address: '0x38b25A89d120B44e3bAc19777E576921319fe9A1',
    chain: 'polygon',
    addressType: 'deposit',
    confidence: 0.99,
    source: 'CoinDCX Statutory Nodal Filing & Proof of Reserves Audit',
    sourceType: 'verified_public_source',
    verificationStatus: 'verified',
    verifiedAt: '2025-10-15T10:30:00Z',
    notes: 'Designated user hot-deposit gateway contract matching CoinDCX custody cluster signature.',
    createdAt: '2025-10-15T10:30:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  // 2. WazirX Ethereum Custody Node (Verified)
  {
    id: 'addr-wazirx-01',
    vaspId: 'vasp-in-02',
    clusterId: 'cluster-wazirx-eth-01',
    address: '0x71C8a77B280f9E0228372bF00000000000003aF9',
    chain: 'ethereum',
    addressType: 'hot_wallet',
    confidence: 0.96,
    source: 'Zanmai Labs FIU Filing & Court Affidavit Case-2025/110',
    sourceType: 'investigator_verified',
    verificationStatus: 'verified',
    verifiedAt: '2025-11-20T14:00:00Z',
    notes: 'Primary escrow and hot withdrawal router node for ERC-20 assets.',
    createdAt: '2025-11-20T14:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  // 3. CoinSwitch Kuber Polygon Address (Verified)
  {
    id: 'addr-coinswitch-01',
    vaspId: 'vasp-in-03',
    clusterId: null,
    address: '0x44c9b21a890e01293810293810293810293811F8',
    chain: 'polygon',
    addressType: 'deposit',
    confidence: 0.94,
    source: 'Bitcipher Labs Public Reserve Attestation',
    sourceType: 'verified_public_source',
    verificationStatus: 'verified',
    verifiedAt: '2025-12-05T09:00:00Z',
    notes: 'Polygon retail investor gateway pool.',
    createdAt: '2025-12-05T09:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  // 4. Binance BSC Custody Node (Verified)
  {
    id: 'addr-binance-01',
    vaspId: 'vasp-global-01',
    clusterId: null,
    address: '0x8849bCd0381099238491029381029381029355C2',
    chain: 'bsc',
    addressType: 'treasury',
    confidence: 0.95,
    source: 'Binance Proof of Reserves Verification',
    sourceType: 'verified_public_source',
    verificationStatus: 'verified',
    verifiedAt: '2025-09-10T12:00:00Z',
    notes: 'Binance multi-asset bridge proxy and hot withdrawal router.',
    createdAt: '2025-09-10T12:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },
  // 5. HTX Tron Hot Pool (Verified)
  {
    id: 'addr-htx-01',
    vaspId: 'vasp-global-02',
    clusterId: 'cluster-htx-tron-01',
    address: 'TWk93zM2sK8Qp6V1nRt8LpX9xLt44zY999',
    chain: 'tron',
    addressType: 'hot_wallet',
    confidence: 0.93,
    source: 'TronScan Exchange Omnibus Attribution Tag',
    sourceType: 'licensed_intelligence_provider',
    verificationStatus: 'verified',
    verifiedAt: '2026-01-18T16:20:00Z',
    notes: 'Identified high-velocity omnibus sweep pool for TRC-20 USDT liquidation.',
    createdAt: '2026-01-18T16:20:00Z',
    updatedAt: '2026-09-10T12:00:00Z',
  },

  // ---------------------------------------------------------------------------
  // SEGREGATED DEMONSTRATION INTELLIGENCE DATASET (Clearly Marked)
  // ---------------------------------------------------------------------------
  {
    id: 'demo-addr-target-01',
    vaspId: 'vasp-in-01',
    clusterId: 'cluster-coindcx-poly-01',
    address: '0x7A91bC84D2697e88b209eB0eAc821639d4A44F82',
    chain: 'tron',
    addressType: 'unknown',
    confidence: 0.60,
    source: 'Smart India Hackathon 2026 Controlled Demonstration Scenario',
    sourceType: 'demo_dataset',
    verificationStatus: 'unverified',
    verifiedAt: null,
    notes: 'Demonstration target wallet representing multi-hop transit seed in controlled hackathon test.',
    createdAt: '2026-09-10T00:00:00Z',
    updatedAt: '2026-09-10T00:00:00Z',
  },
];
